drop table if exists exam301;

-- CREATE TABLE if not exists exam301  (
-- id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
-- title VARCHAR(500),
-- company VARCHAR(500),
-- location VARCHAR(500),
-- url VARCHAR(500),
-- description TEXT
-- );

CREATE TABLE if not exists exam301  (
id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
title TEXT,
company TEXT,
location TEXT,
url TEXT,
description TEXT
);